#!/usr/bin/env python3
"""Split the English transcript into source/, one file per translatable unit.

The unit is a level-2 question and everything under it, so each sidebar story
(level 3) is translated alongside the question it illustrates. A level-1
section becomes one file holding everything up to its first question: the
part's opening page, or the whole section when it has no questions.

source/ is flat because check_parity and make_stubs pair source/ and fa/ by
filename. source/README.md maps every file back to its heading.

Run:  python3 tools/split_book.py
"""

import re
from pathlib import Path

MONOLITH = Path("no-nonsense-zen-for-beginners.md")
SOURCE_DIR = Path("source")

NAMES = {  # level-1 headings that are not parts
    "INTRODUCTION AND HOW TO USE THIS BOOK": "introduction",
    "RESOURCES": "resources",
    "REFERENCES": "references",
    "ACKNOWLEDGMENTS": "acknowledgments",
    "ABOUT THE AUTHOR": "about-the-author",
}


def split(text):
    """Yield (name, heading, chunk). The chunks concatenate back to text."""
    part = question = 0
    for chunk in re.split(r"(?m)^(?=#{1,2} )", text):
        if not chunk:
            continue
        first = chunk.splitlines()[0]
        heading = first.lstrip("# ")
        if not first.startswith("#"):
            name, heading = "front-matter", "Front matter"
        elif first.startswith("## "):
            question += 1
            name = f"{part}-{question:02d}"
        elif heading.startswith("Part "):
            part, question = part + 1, 0
            name = f"part-{part}"
        else:
            name = NAMES[heading]
        yield name, heading, chunk


def main():
    text = MONOLITH.read_text(encoding="utf-8")
    units = list(split(text))
    assert "".join(c for _, _, c in units) == text, "split lost text"
    assert len({n for n, _, _ in units}) == len(units), "duplicate file name"

    SOURCE_DIR.mkdir(exist_ok=True)
    for old in SOURCE_DIR.glob("*.md"):
        old.unlink()
    index = ["# Source files\n", "Generated by `tools/split_book.py`. Book order:\n"]
    for name, heading, chunk in units:
        (SOURCE_DIR / f"{name}.md").write_text(chunk.rstrip() + "\n", encoding="utf-8")
        index.append(f"- [{name}]({name}.md) — {heading}")
    (SOURCE_DIR / "README.md").write_text("\n".join(index) + "\n", encoding="utf-8")
    print(f"{len(units)} files written to {SOURCE_DIR}/")


if __name__ == "__main__":
    main()
